---
title: "**Projects**"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: true
      smooth_scroll: true
---

<head>
  <link rel="stylesheet" href="edwoodbrice_styles" type="text/css">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Raleway" />
<style type="text/css">

<style>

  h1 { 
    font-family: Raleway; 
    font-size: 35px; 
    font-style: normal; 
    font-variant: normal; 
    font-weight: 700; 
    line-height: 26.4px; } 
  
  h3 { 
    font-family: Raleway; 
    font-size: 20px; 
    font-style: normal; 
    font-variant: normal; 
    font-weight: 700; 
    line-height: 15.4px; } 
  
  p, span { 
    font-family: Raleway; 
    font-size: 14px; 
    font-style: normal; 
    font-variant: normal; 
    font-weight: 400; 
    line-height: 20px; } 
    
  section_titles { 
    font-family: Raleway; 
    font-size: 30px; 
    font-style: normal; 
    font-variant: normal; 
    font-weight: 400; 
    line-height: 20px; } 
  
  blockquote { 
    font-family: Raleway; 
    font-size: 25px; 
    font-style: normal; 
    font-variant: normal; 
    font-weight: 400; 
    line-height: 30px; } 
  
  pre { 
    font-family: Raleway; 
    font-size: 18px; 
    font-style: normal; 
    font-variant: normal; 
    font-weight: 400;
    line-height: 18.5714px; }


div.blue { 
  background-color:#e6f0ff; 
  border-radius: 5px; 
  padding: 5px;}

div.card {
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.19);
  padding-top: 30px;
  padding-right: 40px;
  padding-bottom: 15px;
  padding-left: 40px;
  border-radius: 10px;}
</style>


# <section_titles style="color:maroon; font-size: 30px;"> Website Update `r emo::ji("construction")` </section_titles>

<div class="card">
###### <span style="color:black">**Status**: In progress `r emo::ji("building construction")``</span>

<span>
This page is getting an update for 2021! `r emo::ji("snowflake")` </span>
</div>
